server:
  port: 9090
  servlet:
    context-path: /app

spring:
  datasource:    url: jdbc:mysql://127.0.0.1:33060/pandemia
    username: root
    password: secret    driver-class-name: com.mysql.cj.jdbc.Driver
