spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GloballogicServiceAndIntegration/bootcamp2020-solucion-appIntegradora.git
          default-label: 006-Customer
          search-paths:
          - Config
          username: rodrigocayojaGL
          password: Chuchi2010"
server:
  port: 8888
  