server:
  port: 9090
  servlet:
    context-path: /customer/v1
spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:      naming:        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:    name: customer-service
  cloud:    config:      uri:      - localhost:8888
management:  endpoints:    web:      exposure:        include: '*'
eureka:
  client:
    service-url:
      defaultZone: ${defaultZone}   
   
         
        