spring:
    application:
        name: edge-service 

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}      

zuul:
  routes:
    customer-service:
      path: /customer-api/**
      service-id: customer-service
ribbon:
    ReadTimeout: 60000
          